//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacienteAsistente.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asistente()
        {
            this.Tratamientoes = new HashSet<Tratamiento>();
        }
    
        public System.Guid Id { get; set; }
        public string AspNetUserId { get; set; }
        public System.Guid PacienteId { get; set; }
        public string NomAsistente { get; set; }
        public string Telefono { get; set; }
        public string Parentesco { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamiento> Tratamientoes { get; set; }
    }
}
